server:
  tomcat:
    uri-encoding: UTF-8
    # 设置内置Tomcat请求大小为20MB
    max-http-form-post-size: 20MB

logging:
  file:
    name: logs/mailserver.log

  level:
    org.springframework.boot.autoconfigure: error
    root: info

  logback:
    rolling policy:
      max-file-size: 20MB # 文件切割大小
      max-history: 30 # 文档保留天数

spring:
  profiles:
    active: dev

  servlet:
    multipart:
      # 设置请求最大大小为20MB
      max-request-size: 20MB
      # 设置文件上传最大大小为20MB
      max-file-size: 20MB
  # 邮件配置
  mail:
    # 编码格式
    default-encoding: utf-8
    # 协议
    protocol: smtp

token:
  expireDate: 86400000 # 有效期 30 天
  secret: mail
