spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mail?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select '1'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20

logging:
  file:
    name: logs/pop3-server.log

  level:
    org.springframework.boot.autoconfigure: error
    root: info

  logback:
    rolling policy:
      max-file-size: 20MB # 文件切割大小
      max-history: 30 # 文档保留天数

# mybatis-plus相关配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    # 打开延迟加载开关
    lazy-loading-enabled: true
    # 将积极加载改为按需加载
    aggressive-lazy-loading: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.example.pop3server.dao.entity
  global-config:
    db-config:
      id-type: auto

